### ISSUE TITLE
:uri in ctx gives aggregate columns a color

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#79]
![image](https://user-images.githubusercontent.com/124158/36162364-3b33d45e-10b4-11e8-90d5-c6e38afab77b.png)

http://litepay.hyperfiddle.net/ezpjb2RlLWRhdGFiYXNlICJsaXRlcGF5IiwgOmZpZGRsZS1pZCAxNzU5MjE4NjA0NTYzNX0,

**Comment by khardenstine** [comment]
Related: #44

**Comment by dustingetz** [comment]
This appears to have been fixed

**Comment by khardenstine** [comment]
Still an issue, the bindings just have been removed in those links:
![image](https://user-images.githubusercontent.com/7741805/36916498-0fefa16c-1e22-11e8-842a-e991ac4c6e43.png)

**Comment by khardenstine** [comment]
Fixed in https://github.com/hyperfiddle/hyperfiddle/commit/25621937b2f5219e71b36c9addcce64be5d24134#diff-82fd77cde412e54aedadbf58f9663184R49
